include:
  - remote: 'https://raw.githubusercontent.com/marekmoscichowski/gitlab-templates/1.3.6/workflow-default.yml'
  - remote: 'https://raw.githubusercontent.com/marekmoscichowski/gitlab-templates/1.3.6/terraform-toolkit.yml'
  - remote: 'https://raw.githubusercontent.com/marekmoscichowski/gitlab-templates/1.3.6/git-toolkit.yml'

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate
  variables:
    ENVIRONMENTS: examples/complete
    TF_VERSION: 0.15.4

bump-tag:
  extends: .bump_minor_tag
