include:
  - remote: 'https://raw.githubusercontent.com/marekmoscichowski/gitlab-templates/main/workflow-default.yml'
  - remote: 'https://raw.githubusercontent.com/marekmoscichowski/gitlab-templates/main/terraform-toolkit.yml'
  - remote: 'https://raw.githubusercontent.com/marekmoscichowski/gitlab-templates/main/git-toolkit.yml'

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate
  variables:
    ENVIRONMENTS: examples/complete
    TF_VERSION: 0.15.4

bump-tag:
  extends: .bump_minor_tag
