include:
  - project: 'miquido/dev/gitlab-templates'
    ref: 'tags/1.3.6'
    file: 'workflow-default.yml'
  - project: 'miquido/dev/gitlab-templates'
    ref: 'tags/1.3.6'
    file: 'terraform-toolkit.yml'
  - project: 'miquido/dev/gitlab-templates'
    ref: 'tags/1.3.6'
    file: 'git-toolkit.yml'

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate
  variables:
    ENVIRONMENTS: examples/complete
    TF_VERSION: 0.15.4

bump-tag:
  extends: .bump_minor_tag
