version: 2
updates:

  # Maintain dependencies for terraform
  - package-ecosystem: "terraform"
    directory: "/"
    assignees:
      - "marek.moscichowski1"
    schedule:
      interval: "daily"
      time: "8:33"
